version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Shanghai"
      time: "07:30"
    pull-request-branch-name:
      separator: "-"
